In [5]:
import numpy as np
import pandas as pd
import scipy as sc
from sklearn.preprocessing import MinMaxScaler

In [8]:
df=pd.read_csv("Desktop\weatherHistory.csv")
df.head()


Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [10]:
#Standardization 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
col=['Apparent Temperature (C)']
scaled=df[col]
scaled_data=scaler.fit_transform(scaled)
scaled_data

array([[-0.32403547],
       [-0.3390971 ],
       [-0.13810226],
       ...,
       [ 1.04553403],
       [ 0.99723295],
       [ 0.89595648]])

In [12]:
#Normalization
from sklearn.preprocessing import MinMaxScaler

sc=MinMaxScaler()
normal=df[col]
normal_data=sc.fit_transform(normal)
normal_data

array([[0.52348604],
       [0.52108359],
       [0.5531439 ],
       ...,
       [0.7419435 ],
       [0.73423909],
       [0.71808467]])

In [13]:
#Encoding
df['Summary'].unique()

array(['Partly Cloudy', 'Mostly Cloudy', 'Overcast', 'Foggy',
       'Breezy and Mostly Cloudy', 'Clear', 'Breezy and Partly Cloudy',
       'Breezy and Overcast', 'Humid and Mostly Cloudy',
       'Humid and Partly Cloudy', 'Windy and Foggy', 'Windy and Overcast',
       'Breezy and Foggy', 'Windy and Partly Cloudy', 'Breezy',
       'Dry and Partly Cloudy', 'Windy and Mostly Cloudy',
       'Dangerously Windy and Partly Cloudy', 'Dry', 'Windy',
       'Humid and Overcast', 'Light Rain', 'Drizzle', 'Windy and Dry',
       'Dry and Mostly Cloudy', 'Breezy and Dry', 'Rain'], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['Summary1']=label.fit_transform(df['Summary'])
df['Summary1'].unique()

array([19, 17, 18, 12,  3,  6,  5,  4, 13, 15, 23, 25,  2, 26,  0, 11, 24,
        7,  9, 21, 14, 16,  8, 22, 10,  1, 20], dtype=int64)

In [21]:
df['new']=pd.cut(df['Wind Speed (km/h)'],3,labels=['Slow','Medium','Fast'])
df.head(10)

Formatted Date  Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200       19        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200       19        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200       17        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200       19        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200       17        rain         8.755556   
5  2006-04-01 05:00:00.000 +0200       19        rain         9.222222   
6  2006-04-01 06:00:00.000 +0200       19        rain         7.733333   
7  2006-04-01 07:00:00.000 +0200       19        rain         8.772222   
8  2006-04-01 08:00:00.000 +0200       19        rain        10.822222   
9  2006-04-01 09:00:00.000 +0200       19        rain        13.772222   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   
5                  7.111111      0.85            13.9587   
6                  5.522222      0.95            12.3648   
7                  6.527778      0.89            14.1519   
8                 10.822222      0.82            11.3183   
9                 13.772222      0.72            12.5258   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   
5                   258.0          14.9569         0.0               1016.66   
6                   259.0           9.9820         0.0               1016.72   
7                   260.0           9.9820         0.0               1016.84   
8                   259.0           9.9820         0.0               1017.37   
9                   279.0           9.9820         0.0               1017.22   

                       Daily Summary  Summary1   new  
0  Partly cloudy throughout the day.        19  Slow  
1  Partly cloudy throughout the day.        19  Slow  
2  Partly cloudy throughout the day.        17  Slow  
3  Partly cloudy throughout the day.        19  Slow  
4  Partly cloudy throughout the day.        17  Slow  
5  Partly cloudy throughout the day.        19  Slow  
6  Partly cloudy throughout the day.        19  Slow  
7  Partly cloudy throughout the day.        19  Slow  
8  Partly cloudy throughout the day.        19  Slow  
9  Partly cloudy throughout the day.        19  Slow